name: tuturnoapp
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  url_launcher: ^6.0.10
  splash_screen_view: ^3.0.0
  mask_text_input_formatter: ^2.0.0
  intl: ^0.17.0
  flutter_svg: ^0.23.0+1
  responsive_framework: ^0.1.4
  flip_card: ^0.6.0
  

  cupertino_icons: ^1.0.3
  provider: ^6.0.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
      - assets/images/logogristran.png
      - assets/images/wave.svg
      - assets/images/logogris.png
      - assets/images/tuturnoicon.png
      - assets/images/fondo.png
      - assets/images/fondo512.png
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
